-- Supabase (PostgreSQL) Schema Setup
-- Run this in the Supabase SQL Editor

-- 1. Table des trades
CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    action TEXT NOT NULL,
    entry_price REAL,
    exit_price REAL,
    quantity REAL,
    pnl_percent REAL,
    pnl_eur REAL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    reason TEXT,
    strategy_version TEXT,
    rsi_value REAL,
    trend_4h TEXT
);

-- 2. Table pour les trades virtuels (Simulation/Leaderboard)
CREATE TABLE IF NOT EXISTS virtual_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    action TEXT NOT NULL, -- BUY, SELL
    price REAL,
    quantity REAL,
    pnl_percent REAL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    reason TEXT
);

-- 3. Table historique portefeuille
CREATE TABLE IF NOT EXISTS portfolio_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    total_value REAL,
    cash REAL,
    crypto_value REAL,
    positions_count INTEGER
);

-- 4. Table des signaux (pour analyse)
CREATE TABLE IF NOT EXISTS trading_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    signal TEXT NOT NULL,
    price REAL,
    rsi REAL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    executed BOOLEAN DEFAULT FALSE,
    reason TEXT
);

-- 5. Table performance stratégie
CREATE TABLE IF NOT EXISTS strategy_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    strategy_name TEXT,
    win_rate REAL,
    total_trades INTEGER,
    total_pnl REAL
);

-- Création d'index pour optimiser les requêtes
CREATE INDEX IF NOT EXISTS idx_trades_timestamp ON trades(timestamp);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_portfolio_timestamp ON portfolio_history(timestamp);
